sudo: false
dist: trusty

language: php

notifications:
  email: false

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 7.2
  - 5.6
  - 5.4

env:
  - WP_VERSION=latest WP_MULTISITE=0
  - WP_VERSION=latest WP_MULTISITE=1

before_install:
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      cp $HOME/.phpenv/versions/$(phpenv global)/etc/conf.d/xdebug.ini /tmp
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    composer config --list --global
    export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`

install:
  - composer install

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script: vendor/bin/phpunit

jobs:
  fast_finish: true
  include:
    - stage: lint
      script:
        - composer lint
    - stage: coverage
      before_install: skip
      script:
        - composer test -- --coverage-clover=coverage.xml
      after_script:
        - bash <(curl -s https://codecov.io/bash)

stages:
  - lint
  - test
  - coverage
  - deploy
